ALTER VIEW [dbo].[V_DM_TRAI_CHU]
AS
SELECT
tc.ID,tc.MA_TRAI_CHU,tc.TEN_TRAI_CHU,tc.DIA_CHI,tc.MOBILE,tc.FAX,
tc.CMT_GIAY_DKKD,tc.NGAY_CAP_CMT,tc.NOI_CAP_CMT,tc.ID_LOAI_TRAI_CHU,
tc.ID_TRAI_PHIEU_SO_HUU,tc.TEN_NGUOI_DAI_DIEN,tc.CMT_NGUOI_DAI_DIEN,
tc.NGAY_CAP_CMT_NGUOI_DAI_DIEN,tc.NOI_CAP_CMT_NGUOI_DAI_DIEN,tc.CHUC_VU,
tp.MA_TRAI_PHIEU,tp.TEN_TRAI_PHIEU,tp.MENH_GIA,
dbo.f_so_du_trai_phieu_theo_trai_chu( tc.ID,'1/1/1900') as TONG_SO_DU,
dbo.f_so_du_kha_dung_trai_phieu_theo_trai_chu( tc.ID,'1/1/1900') as SO_DU_KHA_DUNG,
tc.SO_TAI_KHOAN,tc.MO_TAI_NGAN_HANG,tc.GHI_CHU1, tc.GHI_CHU2,tc.GHI_CHU3,
tc.ID_NGUOI_DUYET as ID_NGUOI_DUYET_TC,tc.ID_NGUOI_LAP as ID_NGUOI_LAP_TC
,tc.ID_TRANG_THAI,tc.SO_LUONG_TP_SO_HUU_BAN_DAU, tc.NGAY_DUYET
, tc.NGAY_SO_HUU_TRAI_PHIEU
FROM DM_TRAI_CHU tc ,V_DM_TRAI_PHIEU tp
WHERE tc.ID_TRAI_PHIEU_SO_HUU = tp.ID
GO

CREATE FUNCTION [dbo].[f_DM_TRAI_PHIEU_so_luong_trai_phieu_trai_chu_da_so_huu]
(@ID_TRAI_PHIEU DECIMAL)
RETURNS NUMERIC(18,3)
AS
BEGIN
	DECLARE @v_dc_id_so_luong_da_so_huu NUMERIC(18,3)
	DECLARE @v_dc_so_luong_da_duyet NUMERIC(18,3)
	DECLARE @v_dc_so_luong_chua_duyet NUMERIC(18,3)

	SET @v_dc_id_so_luong_da_so_huu = 0
	SET @v_dc_so_luong_da_duyet = (
		SELECT SUM(vdtc.TONG_SO_DU) FROM V_DM_TRAI_CHU vdtc
		WHERE vdtc.ID_TRAI_PHIEU_SO_HUU = @ID_TRAI_PHIEU
		AND vdtc.ID_TRANG_THAI = 61)

	SET @v_dc_so_luong_chua_duyet = (
		SELECT SUM(vdtc.SO_LUONG_TP_SO_HUU_BAN_DAU) FROM V_DM_TRAI_CHU vdtc
		WHERE vdtc.ID_TRAI_PHIEU_SO_HUU = @ID_TRAI_PHIEU
		AND vdtc.ID_TRANG_THAI = 60)
	SET @v_dc_id_so_luong_da_so_huu = @v_dc_so_luong_da_duyet + @v_dc_so_luong_chua_duyet

	RETURN @v_dc_id_so_luong_da_so_huu 	
END

GO
ALTER VIEW [dbo].[V_DM_TRAI_PHIEU]
as
SELECT 
	dtp.ID,
	dtp.ID_DOT_PHAT_HANH, ddph.NGAY_PHAT_HANH, ddph.ID_TO_CHUC_PHAT_HANH, dtcph.TEN_TO_CHUC_PHAT_HANH,
	dtp.MA_TRAI_PHIEU,
	dtp.TEN_TRAI_PHIEU,
	dtp.ID_LOAI_TRAI_PHIEU,(SELECT TEN FROM CM_DM_TU_DIEN cdtd WHERE cdtd.ID = dtp.ID_LOAI_TRAI_PHIEU) AS LOAI_TRAI_PHIEU,
	ddph.MENH_GIA,
	dtp.KY_HAN,
	dtp.ID_DV_KY_HAN,(SELECT cdtd.TEN FROM CM_DM_TU_DIEN cdtd
	                    WHERE cdtd.ID = dtp.ID_DV_KY_HAN) AS DON_VI_KY_HAN,
	dtp.CO_SO_TINH_LAI,
	dtp.LAI_SUAT_DEFAULT,
	dtp.KY_DIEU_CHINH_LS,
	dtp.ID_DV_DIEU_CHINH_LS,(SELECT cdtd.TEN FROM CM_DM_TU_DIEN cdtd
	                    WHERE cdtd.ID = dtp.ID_DV_DIEU_CHINH_LS) AS DON_VI_DIEU_CHINH_LS,
	dtp.THA_NOI_YN,
	dtp.KY_TRA_LAI,
	dtp.ID_DV_KY_TRA_LAI,(SELECT cdtd.TEN FROM CM_DM_TU_DIEN cdtd
	                    WHERE cdtd.ID = dtp.ID_DV_KY_TRA_LAI) AS DON_VI_KY_TRA_LAI,
	dtp.TRA_LAI_SAU_YN,
	dtp.NGAY_DAO_HAN,
	dtp.TONG_SL_PHAT_HANH,
	dtp.TONG_GIA_TRI,
	dtp.BIEN_DO_LAI,
	dtp.SO_NGAY_TCPH_CHUYEN_TIEN_TRUOC,
	dtp.NGUNG_CHUYEN_NHUONG_TU_NGAY_CHOT_YN,
	dtp.NGUNG_CHUYEN_NHUONG_DEN_NGAY_THANH_TOAN_YN,
	dtp.ID_NGUOI_LAP,(SELECT hnsd.TEN
	                    FROM HT_NGUOI_SU_DUNG hnsd WHERE hnsd.ID = dtp.ID_NGUOI_LAP) AS NGUOI_LAP, 
	dtp.ID_NGUOI_DUYET,(SELECT hnsd.TEN
	                    FROM HT_NGUOI_SU_DUNG hnsd WHERE hnsd.ID = dtp.ID_NGUOI_DUYET) AS NGUOI_DUYET,
	dtp.GHI_CHU_PHUONG_THUC_XD_LAI_SUAT,
	dtp.CN_HUONG_THEO_NGAY_CHUYEN_NHUONG_YN,
	dtp.ID_TRANG_THAI, (SELECT cdtd.TEN FROM CM_DM_TU_DIEN cdtd
	                    WHERE cdtd.ID = dtp.ID_TRANG_THAI) AS TRANG_THAI
   ,dtp.SO_HOP_DONG_DL_DK_LUU_KY, dtp.NGAY_KY_HD, dtp.SO_NGAY_CHOT_LAI_TRUOC_NGAY_THANH_TOAN
   , dtp.THANH_TOAN_TRUOC_NGAY_LAM_VIEC_GAN_NHAT_YN
   , dtp.ID_NGAN_HANG_THAM_CHIEU_LAI_SUAT, 
   (SELECT TEN FROM CM_DM_TU_DIEN cdtd 
    WHERE cdtd.ID = dtp.ID_NGAN_HANG_THAM_CHIEU_LAI_SUAT) AS NGAN_HANG_THAM_CHIEU_LS
    , dbo.f_DM_TRAI_PHIEU_so_luong_trai_phieu_trai_chu_da_so_huu (dtp.ID) AS SO_TRAI_PHIEU_TRAI_CHU_DA_SO_HUU
FROM DM_TRAI_PHIEU dtp, DM_DOT_PHAT_HANH ddph, DM_TO_CHUC_PHAT_HANH dtcph
WHERE dtp.ID_DOT_PHAT_HANH = ddph.ID
AND ddph.ID_TO_CHUC_PHAT_HANH = dtcph.ID

GO
ALTER PROCEDURE [dbo].[pr_V_DM_TRAI_PHIEU_Insert]
	@ID_DOT_PHAT_HANH numeric(18, 0),
	@NGAY_PHAT_HANH DATETIME,
	@ID_TO_CHUC_PHAT_HANH numeric(18, 0),
	@TEN_TO_CHUC_PHAT_HANH nvarchar(250),
	@MA_TRAI_PHIEU nvarchar(35),
	@TEN_TRAI_PHIEU nvarchar(250),
	@ID_LOAI_TRAI_PHIEU numeric(18, 0),
	@LOAI_TRAI_PHIEU nvarchar(250),
	@MENH_GIA numeric(21, 3),
	@KY_HAN numeric(4, 0),
	@ID_DV_KY_HAN numeric(18, 0),
	@DON_VI_KY_HAN nvarchar(50),
	@CO_SO_TINH_LAI nvarchar(50),
	@LAI_SUAT_DEFAULT numeric(21, 10),
	@KY_DIEU_CHINH_LS numeric(4, 0),
	@ID_DV_DIEU_CHINH_LS numeric(18, 0),
	@DON_VI_DIEU_CHINH_LS nvarchar(50),
	@THA_NOI_YN nvarchar(1),
	@KY_TRA_LAI numeric(4, 0),
	@ID_DV_KY_TRA_LAI numeric(18, 0),
	@DON_VI_KY_TRA_LAI NVARCHAR(50),
	@TRA_LAI_SAU_YN nvarchar(1),
	@NGAY_DAO_HAN datetime,
	@TONG_SL_PHAT_HANH numeric(18, 0),
	@TONG_GIA_TRI numeric(21, 3),
	@BIEN_DO_LAI numeric(21, 10),
	@SO_NGAY_TCPH_CHUYEN_TIEN_TRUOC numeric(4, 0),
	@NGUNG_CHUYEN_NHUONG_TU_NGAY_CHOT_YN nvarchar(1),
	@NGUNG_CHUYEN_NHUONG_DEN_NGAY_THANH_TOAN_YN nvarchar(1),
	@ID_NGUOI_LAP numeric(18, 0),
	@NGUOI_LAP NVARCHAR(50),
	@ID_NGUOI_DUYET numeric(18, 0),
	@NGUOI_DUYET NVARCHAR(50),
	@GHI_CHU_PHUONG_THUC_XD_LAI_SUAT nvarchar(250),
	@CN_HUONG_THEO_NGAY_CHUYEN_NHUONG_YN nvarchar(1),
	@ID_TRANG_THAI numeric(18, 0),
	@TRANG_THAI nvarchar(50),
	@SO_HOP_DONG_DL_DK_LUU_KY NVARCHAR(250),
	@NGAY_KY_HD DATETIME,
	@SO_NGAY_CHOT_LAI_TRUOC_NGAY_THANH_TOAN numeric(4, 0),
	@THANH_TOAN_TRUOC_NGAY_LAM_VIEC_GAN_NHAT_YN NVARCHAR(1),
	@ID_NGAN_HANG_THAM_CHIEU_LAI_SUAT NUMERIC(18,0),
	@NGAN_HANG_THAM_CHIEU_LS NVARCHAR(250),
	@SO_TRAI_PHIEU_TRAI_CHU_DA_SO_HUU NUMERIC(18,3),
	@ID numeric(18, 0) OUTPUT
	AS 
	INSERT [dbo].[DM_TRAI_PHIEU]
  (
	[ID_DOT_PHAT_HANH],
	[MA_TRAI_PHIEU],
	[TEN_TRAI_PHIEU],
	[ID_LOAI_TRAI_PHIEU],
	[MENH_GIA],
	[KY_HAN],
	[CO_SO_TINH_LAI],
	[ID_DV_KY_HAN],
	[LAI_SUAT_DEFAULT],
	[KY_DIEU_CHINH_LS],
	[ID_DV_DIEU_CHINH_LS],
	[THA_NOI_YN],
	[KY_TRA_LAI],
	[ID_DV_KY_TRA_LAI],
	[TRA_LAI_SAU_YN],
	[NGAY_DAO_HAN],
	[TONG_SL_PHAT_HANH],
	[TONG_GIA_TRI],
	[BIEN_DO_LAI],
	[SO_NGAY_TCPH_CHUYEN_TIEN_TRUOC],
	[NGUNG_CHUYEN_NHUONG_TU_NGAY_CHOT_YN],
	[NGUNG_CHUYEN_NHUONG_DEN_NGAY_THANH_TOAN_YN],
	[ID_NGUOI_LAP],
	[ID_NGUOI_DUYET],
	[GHI_CHU_PHUONG_THUC_XD_LAI_SUAT],
	[CN_HUONG_THEO_NGAY_CHUYEN_NHUONG_YN],
	[ID_TRANG_THAI],
	SO_HOP_DONG_DL_DK_LUU_KY,
	NGAY_KY_HD,
	SO_NGAY_CHOT_LAI_TRUOC_NGAY_THANH_TOAN,
	THANH_TOAN_TRUOC_NGAY_LAM_VIEC_GAN_NHAT_YN,
	ID_NGAN_HANG_THAM_CHIEU_LAI_SUAT
)
VALUES
(
	@ID_DOT_PHAT_HANH,
	@MA_TRAI_PHIEU,
	@TEN_TRAI_PHIEU,
	@ID_LOAI_TRAI_PHIEU,
	@MENH_GIA,
	@KY_HAN,
	@CO_SO_TINH_LAI,
	@ID_DV_KY_HAN,
	@LAI_SUAT_DEFAULT,
	@KY_DIEU_CHINH_LS,
	@ID_DV_DIEU_CHINH_LS,
	@THA_NOI_YN,
	@KY_TRA_LAI,
	@ID_DV_KY_TRA_LAI,
	@TRA_LAI_SAU_YN,
	@NGAY_DAO_HAN,
	@TONG_SL_PHAT_HANH,
	@TONG_GIA_TRI,
	@BIEN_DO_LAI,
	@SO_NGAY_TCPH_CHUYEN_TIEN_TRUOC,
	@NGUNG_CHUYEN_NHUONG_TU_NGAY_CHOT_YN,
	@NGUNG_CHUYEN_NHUONG_DEN_NGAY_THANH_TOAN_YN,
	@ID_NGUOI_LAP,
	@ID_NGUOI_DUYET,
	@GHI_CHU_PHUONG_THUC_XD_LAI_SUAT,
	@CN_HUONG_THEO_NGAY_CHUYEN_NHUONG_YN,
	@ID_TRANG_THAI,
	@SO_HOP_DONG_DL_DK_LUU_KY,
	@NGAY_KY_HD,
	@SO_NGAY_CHOT_LAI_TRUOC_NGAY_THANH_TOAN,
	@THANH_TOAN_TRUOC_NGAY_LAM_VIEC_GAN_NHAT_YN,
	@ID_NGAN_HANG_THAM_CHIEU_LAI_SUAT
)
SELECT @ID=SCOPE_IDENTITY()
GO
ALTER PROCEDURE [dbo].[pr_V_DM_TRAI_PHIEU_Update]
	@ID numeric(18, 0),
	@ID_DOT_PHAT_HANH numeric(18, 0),
	@NGAY_PHAT_HANH DATETIME,
	@ID_TO_CHUC_PHAT_HANH numeric(18, 0),
	@TEN_TO_CHUC_PHAT_HANH nvarchar(250),
	@MA_TRAI_PHIEU nvarchar(35),
	@TEN_TRAI_PHIEU nvarchar(250),
	@ID_LOAI_TRAI_PHIEU numeric(18, 0),
	@LOAI_TRAI_PHIEU nvarchar(250),
	@MENH_GIA numeric(21, 3),
	@KY_HAN numeric(4, 0),
	@ID_DV_KY_HAN numeric(18, 0),
	@DON_VI_KY_HAN nvarchar(50),
	@CO_SO_TINH_LAI nvarchar(50),
	@LAI_SUAT_DEFAULT numeric(21, 10),
	@KY_DIEU_CHINH_LS numeric(4, 0),
	@ID_DV_DIEU_CHINH_LS numeric(18, 0),
	@DON_VI_DIEU_CHINH_LS nvarchar(50),
	@THA_NOI_YN nvarchar(1),
	@KY_TRA_LAI numeric(4, 0),
	@ID_DV_KY_TRA_LAI numeric(18, 0),
	@DON_VI_KY_TRA_LAI NVARCHAR(50),
	@TRA_LAI_SAU_YN nvarchar(1),
	@NGAY_DAO_HAN datetime,
	@TONG_SL_PHAT_HANH numeric(18, 0),
	@TONG_GIA_TRI numeric(21, 3),
	@BIEN_DO_LAI numeric(21, 10),
	@SO_NGAY_TCPH_CHUYEN_TIEN_TRUOC numeric(4, 0),
	@NGUNG_CHUYEN_NHUONG_TU_NGAY_CHOT_YN nvarchar(1),
	@NGUNG_CHUYEN_NHUONG_DEN_NGAY_THANH_TOAN_YN nvarchar(1),
	@ID_NGUOI_LAP numeric(18, 0),
	@NGUOI_LAP NVARCHAR(50),
	@ID_NGUOI_DUYET numeric(18, 0),
	@NGUOI_DUYET NVARCHAR(50),
	@GHI_CHU_PHUONG_THUC_XD_LAI_SUAT nvarchar(250),
	@CN_HUONG_THEO_NGAY_CHUYEN_NHUONG_YN nvarchar(1),
	@ID_TRANG_THAI numeric(18, 0),
	@TRANG_THAI nvarchar(50),
	@SO_HOP_DONG_DL_DK_LUU_KY NVARCHAR(250),
	@NGAY_KY_HD DATETIME,
	@SO_NGAY_CHOT_LAI_TRUOC_NGAY_THANH_TOAN numeric(4, 0),
	@THANH_TOAN_TRUOC_NGAY_LAM_VIEC_GAN_NHAT_YN NVARCHAR(1),
	@ID_NGAN_HANG_THAM_CHIEU_LAI_SUAT NUMERIC(18,0),
	@NGAN_HANG_THAM_CHIEU_LS NVARCHAR(250),
	@SO_TRAI_PHIEU_TRAI_CHU_DA_SO_HUU NUMERIC(18,3)
AS
UPDATE [dbo].[DM_TRAI_PHIEU]
SET 
	[ID_DOT_PHAT_HANH] = @ID_DOT_PHAT_HANH,
	[MA_TRAI_PHIEU] = @MA_TRAI_PHIEU,
	[TEN_TRAI_PHIEU] = @TEN_TRAI_PHIEU,
	[ID_LOAI_TRAI_PHIEU] = @ID_LOAI_TRAI_PHIEU,
	[MENH_GIA] = @MENH_GIA,
	[KY_HAN] = @KY_HAN,
	[CO_SO_TINH_LAI] = @CO_SO_TINH_LAI,
	[ID_DV_KY_HAN] = @ID_DV_KY_HAN,
	[LAI_SUAT_DEFAULT] = @LAI_SUAT_DEFAULT,
	[KY_DIEU_CHINH_LS] = @KY_DIEU_CHINH_LS,
	[ID_DV_DIEU_CHINH_LS] = @ID_DV_DIEU_CHINH_LS,
	[THA_NOI_YN] = @THA_NOI_YN,
	[KY_TRA_LAI] = @KY_TRA_LAI,
	[ID_DV_KY_TRA_LAI] = @ID_DV_KY_TRA_LAI,
	[TRA_LAI_SAU_YN] = @TRA_LAI_SAU_YN,
	[NGAY_DAO_HAN] = @NGAY_DAO_HAN,
	[TONG_SL_PHAT_HANH] = @TONG_SL_PHAT_HANH,
	[TONG_GIA_TRI] = @TONG_GIA_TRI,
	[BIEN_DO_LAI] = @BIEN_DO_LAI,
	[SO_NGAY_TCPH_CHUYEN_TIEN_TRUOC] = @SO_NGAY_TCPH_CHUYEN_TIEN_TRUOC,
	[NGUNG_CHUYEN_NHUONG_TU_NGAY_CHOT_YN] = @NGUNG_CHUYEN_NHUONG_TU_NGAY_CHOT_YN,
	[NGUNG_CHUYEN_NHUONG_DEN_NGAY_THANH_TOAN_YN] = @NGUNG_CHUYEN_NHUONG_DEN_NGAY_THANH_TOAN_YN,
	[ID_NGUOI_LAP] = @ID_NGUOI_LAP,
	[ID_NGUOI_DUYET] = @ID_NGUOI_DUYET,
	[GHI_CHU_PHUONG_THUC_XD_LAI_SUAT] = @GHI_CHU_PHUONG_THUC_XD_LAI_SUAT,
	[CN_HUONG_THEO_NGAY_CHUYEN_NHUONG_YN] = @CN_HUONG_THEO_NGAY_CHUYEN_NHUONG_YN,
	[ID_TRANG_THAI] = @ID_TRANG_THAI,
	[SO_HOP_DONG_DL_DK_LUU_KY] = @SO_HOP_DONG_DL_DK_LUU_KY,
	[NGAY_KY_HD] = @NGAY_KY_HD,
	SO_NGAY_CHOT_LAI_TRUOC_NGAY_THANH_TOAN = @SO_NGAY_CHOT_LAI_TRUOC_NGAY_THANH_TOAN,
	THANH_TOAN_TRUOC_NGAY_LAM_VIEC_GAN_NHAT_YN = @THANH_TOAN_TRUOC_NGAY_LAM_VIEC_GAN_NHAT_YN,
	ID_NGAN_HANG_THAM_CHIEU_LAI_SUAT = @ID_NGAN_HANG_THAM_CHIEU_LAI_SUAT	
WHERE
	[ID] = @ID
GO

ALTER PROCEDURE [dbo].[pr_V_DM_TRAI_CHU_Update]
	@ID numeric(18, 0),
	@MA_TRAI_CHU nvarchar(35),
	@TEN_TRAI_CHU nvarchar(250),
	@DIA_CHI nvarchar(250),
	@MOBILE nvarchar(250),
	@FAX nvarchar(250),
	@CMT_GIAY_DKKD nvarchar(250),
	@NGAY_CAP_CMT datetime,
	@NOI_CAP_CMT nvarchar(50),
	@ID_LOAI_TRAI_CHU numeric(18, 0),
	@ID_TRAI_PHIEU_SO_HUU numeric(18, 0),
	@TEN_NGUOI_DAI_DIEN NVARCHAR(250),
	@CMT_NGUOI_DAI_DIEN NVARCHAR(250),
	@NGAY_CAP_CMT_NGUOI_DAI_DIEN DATETIME, 
	@NOI_CAP_CMT_NGUOI_DAI_DIEN NVARCHAR(250),
	@CHUC_VU NVARCHAR(250),
	@MA_TRAI_PHIEU NVARCHAR(250),
	@TEN_TRAI_PHIEU NVARCHAR(250),
	@MENH_GIA NUMERIC(18,3),
	@TONG_SO_DU NUMERIC(18,3),
	@SO_DU_KHA_DUNG NUMERIC(18,3),
	@SO_TAI_KHOAN nvarchar(250),
	@MO_TAI_NGAN_HANG nvarchar(250),
	@GHI_CHU1 nvarchar(250),
	@GHI_CHU2 nvarchar(250),
	@GHI_CHU3 nvarchar(250),
	@ID_NGUOI_DUYET_TC NUMERIC(18,0),
	@ID_NGUOI_LAP_TC NUMERIC(18,0),
	@ID_TRANG_THAI NUMERIC(18,0),
	@SO_LUONG_TP_SO_HUU_BAN_DAU NUMERIC(18,0),
	@NGAY_DUYET DATETIME,
	@NGAY_SO_HUU_TRAI_PHIEU DATETIME
AS
BEGIN TRAN
UPDATE DM_TRAI_CHU
SET
	-- ID = ? -- this column value is auto-generated,
	MA_TRAI_CHU = @MA_TRAI_CHU,
	TEN_TRAI_CHU = @TEN_TRAI_CHU,
	DIA_CHI = @DIA_CHI,
	MOBILE = @MOBILE,
	FAX = @FAX,
	CMT_GIAY_DKKD = @CMT_GIAY_DKKD,
	NGAY_CAP_CMT = @NGAY_CAP_CMT,
	NOI_CAP_CMT = @NOI_CAP_CMT,
	ID_LOAI_TRAI_CHU = @ID_LOAI_TRAI_CHU,
	SO_TAI_KHOAN = @SO_TAI_KHOAN,
	MO_TAI_NGAN_HANG = @MO_TAI_NGAN_HANG,
	GHI_CHU1 = @GHI_CHU1,
	GHI_CHU2 = @GHI_CHU2,
	GHI_CHU3 = @GHI_CHU3,
	ID_TRAI_PHIEU_SO_HUU = @ID_TRAI_PHIEU_SO_HUU,
	ID_NGUOI_LAP = @ID_NGUOI_LAP_TC,
	ID_NGUOI_DUYET = @ID_NGUOI_DUYET_TC,
	ID_TRANG_THAI = @ID_TRANG_THAI,
	TEN_NGUOI_DAI_DIEN = @TEN_NGUOI_DAI_DIEN,
	CMT_NGUOI_DAI_DIEN = @CMT_NGUOI_DAI_DIEN,
	NGAY_CAP_CMT_NGUOI_DAI_DIEN = @NGAY_CAP_CMT_NGUOI_DAI_DIEN,
	NOI_CAP_CMT_NGUOI_DAI_DIEN = @NOI_CAP_CMT_NGUOI_DAI_DIEN,
	CHUC_VU = @CHUC_VU,
	SO_LUONG_TP_SO_HUU_BAN_DAU = @SO_LUONG_TP_SO_HUU_BAN_DAU,
	NGAY_SO_HUU_TRAI_PHIEU = @NGAY_SO_HUU_TRAI_PHIEU
WHERE ID = @ID

-- Neu day la su kien DUYET
IF @ID_NGUOI_DUYET_TC IS NOT NULL 
BEGIN
	UPDATE DM_TRAI_CHU
SET NGAY_DUYET = @NGAY_DUYET
	WHERE ID = @ID
	
	EXEC pr_GD_SO_DU_TRAI_PHIEU_add_so_du
	@date = @NGAY_SO_HUU_TRAI_PHIEU,
	@ip_dc_trai_chu_id = @ID,
	@add_value_tong_so_du = @SO_LUONG_TP_SO_HUU_BAN_DAU,
	@add_value_so_du_kha_dung = @SO_LUONG_TP_SO_HUU_BAN_DAU
END

IF @@ERROR !=0 ROLLBACK TRAN
ELSE COMMIT TRAN
GO
ALTER PROCEDURE [dbo].[pr_DM_TRAI_CHU_IMP_Insert_Import]
	@ID DECIMAL,
	@MA_TRAI_CHU nvarchar(50),
	@TEN_TRAI_CHU nvarchar(250),
	@DKHD_CMND nvarchar(50),
	@NGAY_CAP datetime,
	@NOI_CAP nvarchar(250),
	@DIA_CHI nvarchar(250),
	@DIEN_THOAI nvarchar(50),
	@ID_LOAI_TRAI_CHU DECIMAL,
	@SO_TAI_KHOAN nvarchar(50),
	@NOI_MO_TAI_KHOAN nvarchar(250),
	@ID_TRAI_PHIEU_SO_HUU DECIMAL,
	@TEN_NGUOI_DAI_DIEN NVARCHAR(250),
	@CMT_NGUOI_DAI_DIEN NVARCHAR(50),
	@NGAY_CAP_CMT_NGUOI_DAI_DIEN DATETIME,
	@NOI_CAP_CMT_NGUOI_DAI_DIEN NVARCHAR(250),
	@CHUC_VU NVARCHAR(150),
	@SO_LUONG_TRAI_PHIEU_SO_HUU numeric(18, 0),
	@NGAY_BAT_DAU_SO_HUU_TP DATETIME,
	@ID_NGUOI_LAP DECIMAL
AS
IF @NGAY_CAP = '1/1/1900' SET @NGAY_CAP = NULL
IF @NGAY_CAP_CMT_NGUOI_DAI_DIEN = '1/1/1900' SET @NGAY_CAP_CMT_NGUOI_DAI_DIEN = NULL
 --IF @LOAI_HINH_CO_CONG = 3 SET @ID_LOAI_TRAI_CHU = 32
 --else IF @LOAI_HINH_CO_CONG = 4 SET @ID_LOAI_TRAI_CHU = 40
 --else IF @LOAI_HINH_CO_CONG = 5 SET @ID_LOAI_TRAI_CHU = 31
 --ELSE IF @LOAI_HINH_CO_CONG = 6 SET @ID_LOAI_TRAI_CHU = 39
 BEGIN TRAN

-- 1. Chèn thông tin vào trái ch?
 INSERT INTO DM_TRAI_CHU
 (
 	-- ID -- this column value is auto-generated,
 	MA_TRAI_CHU,
 	TEN_TRAI_CHU,
 	DIA_CHI,
 	MOBILE,
 	FAX,
 	CMT_GIAY_DKKD,
 	NGAY_CAP_CMT,
 	NOI_CAP_CMT,
 	ID_LOAI_TRAI_CHU,
 	SO_TAI_KHOAN,
 	MO_TAI_NGAN_HANG,
 	GHI_CHU1,
 	GHI_CHU2,
 	GHI_CHU3,
 	ID_TRAI_PHIEU_SO_HUU,
 	ID_NGUOI_LAP,
 	ID_NGUOI_DUYET,
 	ID_TRANG_THAI,
 	TEN_NGUOI_DAI_DIEN,
 	CMT_NGUOI_DAI_DIEN,
 	NGAY_CAP_CMT_NGUOI_DAI_DIEN,
 	NOI_CAP_CMT_NGUOI_DAI_DIEN,
 	CHUC_VU,
 	SO_LUONG_TP_SO_HUU_BAN_DAU,
 	NGAY_SO_HUU_TRAI_PHIEU
 )
 VALUES
 (
 	/* MA_TRAI_CHU	*/@MA_TRAI_CHU,
 	/* TEN_TRAI_CHU	*/@TEN_TRAI_CHU,
 	/* DIA_CHI	*/@DIA_CHI,
 	/* MOBILE	*/@DIEN_THOAI,
 	/* FAX	*/'',
 	/* CMT_GIAY_DKKD	*/@DKHD_CMND,
 	/* NGAY_CAP_CMT	*/@NGAY_CAP,
 	/* NOI_CAP_CMT	*/@NOI_CAP,
 	/* ID_LOAI_TRAI_CHU	*/@ID_LOAI_TRAI_CHU,
 	/* SO_TAI_KHOAN	*/@SO_TAI_KHOAN,
 	/* MO_TAI_NGAN_HANG	*/@NOI_MO_TAI_KHOAN,
 	/* GHI_CHU1	*/'',
 	/* GHI_CHU2	*/'',
 	/* GHI_CHU3	*/'',
 	/* ID_TRAI_PHIEU_SO_HUU	*/@ID_TRAI_PHIEU_SO_HUU,  -- STT s? l?y d? d?ng ID_TRAI_PHIEU
 	/* ID_NGUOI_LAP	*/@ID_NGUOI_LAP,
 	/* ID_NGUOI_DUYET	*/@ID_NGUOI_LAP,
 	/* ID_TRANG_THAI	*/60,
 	@TEN_NGUOI_DAI_DIEN,
 	@CMT_NGUOI_DAI_DIEN,
 	@NGAY_CAP_CMT_NGUOI_DAI_DIEN,
 	@NOI_CAP_CMT_NGUOI_DAI_DIEN,
 	@CHUC_VU,
 	@SO_LUONG_TRAI_PHIEU_SO_HUU,
 	@NGAY_BAT_DAU_SO_HUU_TP
 )
 SELECT @ID=SCOPE_IDENTITY()

IF( @@ERROR!=0) ROLLBACK TRAN
ELSE COMMIT TRAN
GO
