///************************************************
/// Generated by: NinhVH
/// Date: 25/10/2012 09:59:21
/// Goal: Create Form for GD_THONG_BAO_LAI_SUAT_IN_TIMES
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;
using IP.Core.IPSystemAdmin;
using BondUS;
using BondDS;
using BondDS.CDBNames;

using C1.Win.C1FlexGrid;
using IP.Core.IPExcelReport;

namespace BondApp
{



	public class f657_thong_bao_lai_suat_in_times : System.Windows.Forms.Form
	{
		internal System.Windows.Forms.ImageList ImageList;
		internal System.Windows.Forms.Panel m_pnl_out_place_dm;
        private C1.Win.C1FlexGrid.C1FlexGrid m_fg;
        internal SIS.Controls.Button.SiSButton m_cmd_exit;
        private GroupBox m_gru_thong_tin_cap_nhat;
        private DateTimePicker m_date_den_ngay;
        private DateTimePicker m_date_tu_ngay;
        private Label label6;
        private Label label5;
        private GroupBox m_gru_thong_tin_trai_phieu;
        private Label label34;
        private Label m_lbl_to_chuc_phat_hanh;
        private Label m_lbl_menh_gia;
        private Label m_lbl_ngay_phat_hanh;
        private TextBox m_txt_to_chuc_phat_hanh;
        private TextBox m_txt_menh_gia;
        private Button m_cmd_chon_trai_phieu;
        private TextBox m_txt_ten_trai_phieu;
        private Label m_lbl_title;
        internal SIS.Controls.Button.SiSButton m_cmd_export_excel;
		private System.ComponentModel.IContainer components;

		public f657_thong_bao_lai_suat_in_times()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
			format_controls();
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f657_thong_bao_lai_suat_in_times));
            this.ImageList = new System.Windows.Forms.ImageList(this.components);
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_export_excel = new SIS.Controls.Button.SiSButton();
            this.m_cmd_exit = new SIS.Controls.Button.SiSButton();
            this.m_fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.m_gru_thong_tin_cap_nhat = new System.Windows.Forms.GroupBox();
            this.m_date_den_ngay = new System.Windows.Forms.DateTimePicker();
            this.m_date_tu_ngay = new System.Windows.Forms.DateTimePicker();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.m_gru_thong_tin_trai_phieu = new System.Windows.Forms.GroupBox();
            this.label34 = new System.Windows.Forms.Label();
            this.m_lbl_to_chuc_phat_hanh = new System.Windows.Forms.Label();
            this.m_lbl_menh_gia = new System.Windows.Forms.Label();
            this.m_lbl_ngay_phat_hanh = new System.Windows.Forms.Label();
            this.m_txt_to_chuc_phat_hanh = new System.Windows.Forms.TextBox();
            this.m_txt_menh_gia = new System.Windows.Forms.TextBox();
            this.m_cmd_chon_trai_phieu = new System.Windows.Forms.Button();
            this.m_txt_ten_trai_phieu = new System.Windows.Forms.TextBox();
            this.m_lbl_title = new System.Windows.Forms.Label();
            this.m_pnl_out_place_dm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).BeginInit();
            this.m_gru_thong_tin_cap_nhat.SuspendLayout();
            this.m_gru_thong_tin_trai_phieu.SuspendLayout();
            this.SuspendLayout();
            // 
            // ImageList
            // 
            this.ImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ImageList.ImageStream")));
            this.ImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.ImageList.Images.SetKeyName(0, "");
            this.ImageList.Images.SetKeyName(1, "");
            this.ImageList.Images.SetKeyName(2, "");
            this.ImageList.Images.SetKeyName(3, "");
            this.ImageList.Images.SetKeyName(4, "");
            this.ImageList.Images.SetKeyName(5, "");
            this.ImageList.Images.SetKeyName(6, "");
            this.ImageList.Images.SetKeyName(7, "");
            this.ImageList.Images.SetKeyName(8, "");
            this.ImageList.Images.SetKeyName(9, "");
            this.ImageList.Images.SetKeyName(10, "");
            this.ImageList.Images.SetKeyName(11, "");
            this.ImageList.Images.SetKeyName(12, "");
            this.ImageList.Images.SetKeyName(13, "");
            this.ImageList.Images.SetKeyName(14, "");
            this.ImageList.Images.SetKeyName(15, "");
            this.ImageList.Images.SetKeyName(16, "");
            this.ImageList.Images.SetKeyName(17, "");
            this.ImageList.Images.SetKeyName(18, "");
            this.ImageList.Images.SetKeyName(19, "");
            this.ImageList.Images.SetKeyName(20, "");
            this.ImageList.Images.SetKeyName(21, "");
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_export_excel);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_exit);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 526);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(784, 36);
            this.m_pnl_out_place_dm.TabIndex = 19;
            // 
            // m_cmd_export_excel
            // 
            this.m_cmd_export_excel.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_export_excel.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_export_excel.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_export_excel.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_export_excel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_export_excel.ImageIndex = 19;
            this.m_cmd_export_excel.ImageList = this.ImageList;
            this.m_cmd_export_excel.Location = new System.Drawing.Point(4, 4);
            this.m_cmd_export_excel.Name = "m_cmd_export_excel";
            this.m_cmd_export_excel.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_export_excel.TabIndex = 23;
            this.m_cmd_export_excel.Text = "Xuất excel";
            // 
            // m_cmd_exit
            // 
            this.m_cmd_exit.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_exit.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_exit.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_exit.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_exit.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_exit.ImageIndex = 12;
            this.m_cmd_exit.ImageList = this.ImageList;
            this.m_cmd_exit.Location = new System.Drawing.Point(692, 4);
            this.m_cmd_exit.Name = "m_cmd_exit";
            this.m_cmd_exit.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_exit.TabIndex = 11;
            this.m_cmd_exit.Text = "Thoát (Esc)";
            // 
            // m_fg
            // 
            this.m_fg.ColumnInfo = resources.GetString("m_fg.ColumnInfo");
            this.m_fg.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_fg.Location = new System.Drawing.Point(0, 198);
            this.m_fg.Name = "m_fg";
            this.m_fg.Size = new System.Drawing.Size(784, 328);
            this.m_fg.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg.Styles"));
            this.m_fg.TabIndex = 20;
            // 
            // m_gru_thong_tin_cap_nhat
            // 
            this.m_gru_thong_tin_cap_nhat.Controls.Add(this.m_date_den_ngay);
            this.m_gru_thong_tin_cap_nhat.Controls.Add(this.m_date_tu_ngay);
            this.m_gru_thong_tin_cap_nhat.Controls.Add(this.label6);
            this.m_gru_thong_tin_cap_nhat.Controls.Add(this.label5);
            this.m_gru_thong_tin_cap_nhat.Dock = System.Windows.Forms.DockStyle.Top;
            this.m_gru_thong_tin_cap_nhat.Location = new System.Drawing.Point(0, 145);
            this.m_gru_thong_tin_cap_nhat.Name = "m_gru_thong_tin_cap_nhat";
            this.m_gru_thong_tin_cap_nhat.Size = new System.Drawing.Size(784, 55);
            this.m_gru_thong_tin_cap_nhat.TabIndex = 22;
            this.m_gru_thong_tin_cap_nhat.TabStop = false;
            this.m_gru_thong_tin_cap_nhat.Text = "Thông tin truy xuất";
            // 
            // m_date_den_ngay
            // 
            this.m_date_den_ngay.Checked = false;
            this.m_date_den_ngay.CustomFormat = "dd/MM/yyyy";
            this.m_date_den_ngay.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.m_date_den_ngay.Location = new System.Drawing.Point(457, 19);
            this.m_date_den_ngay.Name = "m_date_den_ngay";
            this.m_date_den_ngay.Size = new System.Drawing.Size(130, 20);
            this.m_date_den_ngay.TabIndex = 10;
            // 
            // m_date_tu_ngay
            // 
            this.m_date_tu_ngay.Checked = false;
            this.m_date_tu_ngay.CustomFormat = "dd/MM/yyyy";
            this.m_date_tu_ngay.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.m_date_tu_ngay.Location = new System.Drawing.Point(198, 19);
            this.m_date_tu_ngay.Name = "m_date_tu_ngay";
            this.m_date_tu_ngay.Size = new System.Drawing.Size(130, 20);
            this.m_date_tu_ngay.TabIndex = 10;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(379, 22);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(53, 13);
            this.label6.TabIndex = 11;
            this.label6.Text = "Đến ngày";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(52, 22);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(125, 13);
            this.label5.TabIndex = 11;
            this.label5.Text = "Truy xuất lãi suất từ ngày";
            // 
            // m_gru_thong_tin_trai_phieu
            // 
            this.m_gru_thong_tin_trai_phieu.Controls.Add(this.label34);
            this.m_gru_thong_tin_trai_phieu.Controls.Add(this.m_lbl_to_chuc_phat_hanh);
            this.m_gru_thong_tin_trai_phieu.Controls.Add(this.m_lbl_menh_gia);
            this.m_gru_thong_tin_trai_phieu.Controls.Add(this.m_lbl_ngay_phat_hanh);
            this.m_gru_thong_tin_trai_phieu.Controls.Add(this.m_txt_to_chuc_phat_hanh);
            this.m_gru_thong_tin_trai_phieu.Controls.Add(this.m_txt_menh_gia);
            this.m_gru_thong_tin_trai_phieu.Controls.Add(this.m_cmd_chon_trai_phieu);
            this.m_gru_thong_tin_trai_phieu.Controls.Add(this.m_txt_ten_trai_phieu);
            this.m_gru_thong_tin_trai_phieu.Dock = System.Windows.Forms.DockStyle.Top;
            this.m_gru_thong_tin_trai_phieu.Location = new System.Drawing.Point(0, 45);
            this.m_gru_thong_tin_trai_phieu.Name = "m_gru_thong_tin_trai_phieu";
            this.m_gru_thong_tin_trai_phieu.Size = new System.Drawing.Size(784, 100);
            this.m_gru_thong_tin_trai_phieu.TabIndex = 21;
            this.m_gru_thong_tin_trai_phieu.TabStop = false;
            this.m_gru_thong_tin_trai_phieu.Text = "Thông tin trái phiếu";
            // 
            // label34
            // 
            this.label34.AutoSize = true;
            this.label34.Location = new System.Drawing.Point(337, 50);
            this.label34.Name = "label34";
            this.label34.Size = new System.Drawing.Size(30, 13);
            this.label34.TabIndex = 56;
            this.label34.Text = "VNĐ";
            this.label34.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // m_lbl_to_chuc_phat_hanh
            // 
            this.m_lbl_to_chuc_phat_hanh.AutoSize = true;
            this.m_lbl_to_chuc_phat_hanh.Location = new System.Drawing.Point(60, 22);
            this.m_lbl_to_chuc_phat_hanh.Name = "m_lbl_to_chuc_phat_hanh";
            this.m_lbl_to_chuc_phat_hanh.Size = new System.Drawing.Size(72, 13);
            this.m_lbl_to_chuc_phat_hanh.TabIndex = 34;
            this.m_lbl_to_chuc_phat_hanh.Text = "Tên trái phiếu";
            this.m_lbl_to_chuc_phat_hanh.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // m_lbl_menh_gia
            // 
            this.m_lbl_menh_gia.AutoSize = true;
            this.m_lbl_menh_gia.Location = new System.Drawing.Point(60, 50);
            this.m_lbl_menh_gia.Name = "m_lbl_menh_gia";
            this.m_lbl_menh_gia.Size = new System.Drawing.Size(51, 13);
            this.m_lbl_menh_gia.TabIndex = 35;
            this.m_lbl_menh_gia.Text = "Mệnh giá";
            this.m_lbl_menh_gia.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // m_lbl_ngay_phat_hanh
            // 
            this.m_lbl_ngay_phat_hanh.AutoSize = true;
            this.m_lbl_ngay_phat_hanh.Location = new System.Drawing.Point(60, 75);
            this.m_lbl_ngay_phat_hanh.Name = "m_lbl_ngay_phat_hanh";
            this.m_lbl_ngay_phat_hanh.Size = new System.Drawing.Size(98, 13);
            this.m_lbl_ngay_phat_hanh.TabIndex = 37;
            this.m_lbl_ngay_phat_hanh.Text = "Tổ chức phát hành";
            this.m_lbl_ngay_phat_hanh.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // m_txt_to_chuc_phat_hanh
            // 
            this.m_txt_to_chuc_phat_hanh.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.m_txt_to_chuc_phat_hanh.Location = new System.Drawing.Point(158, 72);
            this.m_txt_to_chuc_phat_hanh.Name = "m_txt_to_chuc_phat_hanh";
            this.m_txt_to_chuc_phat_hanh.ReadOnly = true;
            this.m_txt_to_chuc_phat_hanh.Size = new System.Drawing.Size(429, 20);
            this.m_txt_to_chuc_phat_hanh.TabIndex = 44;
            this.m_txt_to_chuc_phat_hanh.TabStop = false;
            // 
            // m_txt_menh_gia
            // 
            this.m_txt_menh_gia.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.m_txt_menh_gia.Location = new System.Drawing.Point(158, 45);
            this.m_txt_menh_gia.Name = "m_txt_menh_gia";
            this.m_txt_menh_gia.ReadOnly = true;
            this.m_txt_menh_gia.Size = new System.Drawing.Size(170, 20);
            this.m_txt_menh_gia.TabIndex = 44;
            this.m_txt_menh_gia.TabStop = false;
            this.m_txt_menh_gia.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // m_cmd_chon_trai_phieu
            // 
            this.m_cmd_chon_trai_phieu.Location = new System.Drawing.Point(593, 17);
            this.m_cmd_chon_trai_phieu.Name = "m_cmd_chon_trai_phieu";
            this.m_cmd_chon_trai_phieu.Size = new System.Drawing.Size(33, 23);
            this.m_cmd_chon_trai_phieu.TabIndex = 2;
            this.m_cmd_chon_trai_phieu.Text = "...";
            this.m_cmd_chon_trai_phieu.UseVisualStyleBackColor = true;
            // 
            // m_txt_ten_trai_phieu
            // 
            this.m_txt_ten_trai_phieu.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.m_txt_ten_trai_phieu.Location = new System.Drawing.Point(158, 19);
            this.m_txt_ten_trai_phieu.Name = "m_txt_ten_trai_phieu";
            this.m_txt_ten_trai_phieu.ReadOnly = true;
            this.m_txt_ten_trai_phieu.Size = new System.Drawing.Size(429, 20);
            this.m_txt_ten_trai_phieu.TabIndex = 44;
            this.m_txt_ten_trai_phieu.TabStop = false;
            // 
            // m_lbl_title
            // 
            this.m_lbl_title.Dock = System.Windows.Forms.DockStyle.Top;
            this.m_lbl_title.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_title.ForeColor = System.Drawing.Color.Maroon;
            this.m_lbl_title.Location = new System.Drawing.Point(0, 0);
            this.m_lbl_title.Name = "m_lbl_title";
            this.m_lbl_title.Size = new System.Drawing.Size(784, 45);
            this.m_lbl_title.TabIndex = 23;
            this.m_lbl_title.Text = "F657 - Báo cáo lãi suất trái phiếu";
            this.m_lbl_title.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // f657_thong_bao_lai_suat_in_times
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(784, 562);
            this.Controls.Add(this.m_gru_thong_tin_cap_nhat);
            this.Controls.Add(this.m_gru_thong_tin_trai_phieu);
            this.Controls.Add(this.m_lbl_title);
            this.Controls.Add(this.m_fg);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.Name = "f657_thong_bao_lai_suat_in_times";
            this.Text = "F657 - Báo cáo lãi suất trái phiếu";
            this.Load += new System.EventHandler(this.f657_thong_bao_lai_suat_in_times_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).EndInit();
            this.m_gru_thong_tin_cap_nhat.ResumeLayout(false);
            this.m_gru_thong_tin_cap_nhat.PerformLayout();
            this.m_gru_thong_tin_trai_phieu.ResumeLayout(false);
            this.m_gru_thong_tin_trai_phieu.PerformLayout();
            this.ResumeLayout(false);

		}
		#endregion

		#region Public Interface
		public void display(){			
			this.ShowDialog();
		}
		#endregion

		#region Data Structure
		private enum e_col_Number{
            STT = 1,
			NGAY_KET_THUC = 3
,LAI_SUAT = 5
,SO_NGAY_AP_DUNG = 4
,NGAY_DAU = 2
,GHI_CHU = 6

		}			
		#endregion

		#region Members
		ITransferDataRow m_obj_trans;		
		DS_GD_THONG_BAO_LAI_SUAT_IN_TIMES m_ds = new DS_GD_THONG_BAO_LAI_SUAT_IN_TIMES();
		US_GD_THONG_BAO_LAI_SUAT_IN_TIMES m_us = new US_GD_THONG_BAO_LAI_SUAT_IN_TIMES();
        US_V_DM_TRAI_PHIEU m_us_v_trai_phieu = new US_V_DM_TRAI_PHIEU();
        DS_V_DM_TRAI_PHIEU m_ds_v_trai_phieu = new DS_V_DM_TRAI_PHIEU();
		#endregion

		#region Private Methods
		private void format_controls(){
            CControlFormat.setFormStyle(this, new CAppContext_201(), IPFormStyle.DialogForm);
            CControlFormat.setC1FlexFormat(m_fg);
            CGridUtils.AddSave_Excel_Handlers(m_fg);
            CGridUtils.AddSearch_Handlers(m_fg);
            this.KeyPreview = true;
            m_lbl_title.Font = new Font("Arial", 16);
            m_lbl_title.ForeColor = Color.DarkRed;
            m_lbl_title.TextAlign = ContentAlignment.MiddleCenter;
            set_define_events();	
		}
		private void set_initial_form_load(){						
			m_obj_trans = get_trans_object(m_fg);			
            m_date_tu_ngay.Value = DateTime.Today.AddDays(-30);
            m_date_den_ngay.Value = DateTime.Today.AddDays(30);
		}	
		private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg){
			Hashtable v_htb = new Hashtable();
			v_htb.Add(GD_THONG_BAO_LAI_SUAT_IN_TIMES.NGAY_KET_THUC, e_col_Number.NGAY_KET_THUC);
			v_htb.Add(GD_THONG_BAO_LAI_SUAT_IN_TIMES.LAI_SUAT, e_col_Number.LAI_SUAT);
			v_htb.Add(GD_THONG_BAO_LAI_SUAT_IN_TIMES.SO_NGAY_AP_DUNG, e_col_Number.SO_NGAY_AP_DUNG);
			v_htb.Add(GD_THONG_BAO_LAI_SUAT_IN_TIMES.NGAY_DAU, e_col_Number.NGAY_DAU);
			v_htb.Add(GD_THONG_BAO_LAI_SUAT_IN_TIMES.GHI_CHU, e_col_Number.GHI_CHU);
									
			ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg,v_htb,m_ds.GD_THONG_BAO_LAI_SUAT_IN_TIMES.NewRow());
			return v_obj_trans;			
		}
		private void load_data_2_grid(){						
			m_ds = new DS_GD_THONG_BAO_LAI_SUAT_IN_TIMES();
            m_us.fill_dataset_by_trai_phieu_in_times_tron_ky(m_ds, m_date_tu_ngay.Value, m_date_den_ngay.Value, m_us_v_trai_phieu.dcID);
			m_fg.Redraw = false;
			CGridUtils.Dataset2C1Grid(m_ds, m_fg, m_obj_trans);
            CGridUtils.MakeSoTT((int)e_col_Number.STT, m_fg);
			m_fg.Redraw = true;
		}
		private void grid2us_object(US_GD_THONG_BAO_LAI_SUAT_IN_TIMES i_us
			, int i_grid_row) {
			DataRow v_dr;
			v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			m_obj_trans.GridRow2DataRow(i_grid_row,v_dr);
			i_us.DataRow2Me(v_dr);
		}

	
		private void us_object2grid(US_GD_THONG_BAO_LAI_SUAT_IN_TIMES i_us
			, int i_grid_row) {
			DataRow v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			i_us.Me2DataRow(v_dr);
			m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
		}

        private void select_trai_phieu()
        {
            f300_dm_trai_phieu v_frm300 = new f300_dm_trai_phieu();
            m_us_v_trai_phieu = v_frm300.select_trai_phieu();
            if (!m_us_v_trai_phieu.IsIDNull())
                us_trai_phieu_2_form();
        }

        private void us_trai_phieu_2_form()
        {
            if (m_us_v_trai_phieu != null)
            {                
                m_txt_ten_trai_phieu.Text = m_us_v_trai_phieu.strTEN_TRAI_PHIEU;
                m_txt_menh_gia.Text = CIPConvert.ToStr(m_us_v_trai_phieu.dcMENH_GIA, "#,###");
                m_txt_to_chuc_phat_hanh.Text = m_us_v_trai_phieu.strTEN_TO_CHUC_PHAT_HANH;                               
            }
        }		
		
        private void export_excel()
        {
            CExcelReport v_obj_export_excel = new CExcelReport("f750_Bao cao lai suat trai phieu.xls", 12, 2);
            v_obj_export_excel.AddFindAndReplaceItem("<NGAY_BAT_DAU>", CIPConvert.ToStr(m_date_tu_ngay.Value, "dd/MM/yyyy"));
            v_obj_export_excel.AddFindAndReplaceItem("<TEN_CONG_TY>", m_txt_to_chuc_phat_hanh.Text);
            v_obj_export_excel.AddFindAndReplaceItem("<NGAY_KET_THUC>", CIPConvert.ToStr(m_date_den_ngay.Value, "dd/MM/yyyy"));
            v_obj_export_excel.AddFindAndReplaceItem("<TONG_SO_NGAY>", CIPConvert.ToStr(get_tong_so_ngay(), "#,###"));            
            v_obj_export_excel.FindAndReplace(false);
            v_obj_export_excel.Export2ExcelWithoutFixedRows(m_fg, (int)e_col_Number.STT, m_fg.Cols.Count - 1, false);
        }
        private decimal get_tong_so_ngay()
        {
            decimal v_sum = 0;
            for (int i = 0; i < m_ds.GD_THONG_BAO_LAI_SUAT_IN_TIMES.Count; i++)
            {
                v_sum = v_sum + m_ds.GD_THONG_BAO_LAI_SUAT_IN_TIMES[i].SO_NGAY_AP_DUNG;
            }
            return v_sum;
        }
		private void view_gd_thong_bao_lai_suat_in_times(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			grid2us_object(m_us, m_fg.Row);
		//	f657_thong_bao_lai_suat_in_times_DE v_fDE = new f657_thong_bao_lai_suat_in_times_DE();			
		//	v_fDE.display(m_us);
		}		
		#endregion

//
		//
		//		EVENT HANLDERS
		//
        //
        #region Evens
        private void set_define_events()
        {
            m_cmd_exit.Click += new EventHandler(m_cmd_exit_Click);
            m_cmd_chon_trai_phieu.Click += new EventHandler(m_cmd_chon_trai_phieu_Click);
            m_date_tu_ngay.ValueChanged += new EventHandler(m_date_tu_ngay_ValueChanged);
            m_date_den_ngay.ValueChanged += new EventHandler(m_date_den_ngay_ValueChanged);
            m_cmd_export_excel.Click += new EventHandler(m_cmd_export_excel_Click);
            this.KeyDown += new KeyEventHandler(f657_thong_bao_lai_suat_in_times_KeyDown);
        }

        void f657_thong_bao_lai_suat_in_times_KeyDown(object sender, KeyEventArgs e)
        {
            try
            {
                if (e.KeyCode == Keys.Escape)
                    this.Close();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        void m_cmd_export_excel_Click(object sender, EventArgs e)
        {
            try
            {
                export_excel();
            }
            catch (Exception v_e)
            {
                
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        void m_date_den_ngay_ValueChanged(object sender, EventArgs e)
        {
            try
            {
                load_data_2_grid();
            }
            catch (Exception v_e)
            {
                
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        void m_date_tu_ngay_ValueChanged(object sender, EventArgs e)
        {
            try
            {
                load_data_2_grid();
            }
            catch (Exception v_e)
            {
                
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        void m_cmd_chon_trai_phieu_Click(object sender, EventArgs e)
        {
            try
            {
                select_trai_phieu();
                load_data_2_grid();
            }
            catch (Exception v_e)
            {

                CSystemLog_301.ExceptionHandle(v_e);
            }
        }
		private void f657_thong_bao_lai_suat_in_times_Load(object sender, System.EventArgs e) {
			try{
				set_initial_form_load();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		
		}

		private void m_cmd_exit_Click(object sender, EventArgs e) {
			try{
				this.Close();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
        }
        #endregion
    }
}

