///************************************************
/// Generated by: uyvq
/// Date: 08/09/2012 09:37:14
/// Goal: Create User Service Class for RPT_NHAC_VIEC
///************************************************
/// <summary>
/// Create User Service Class for RPT_NHAC_VIEC
/// </summary>


using BondDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using System;
namespace BondUS
{

public class US_RPT_NHAC_VIEC : US_Object
{
	private const string c_TableName = "RPT_NHAC_VIEC";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_NGUOI_XEM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_XEM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NGUOI_XEM"] = value;
		}
	}

	public bool IsID_NGUOI_XEMNull()	{
		return pm_objDR.IsNull("ID_NGUOI_XEM");
	}

	public void SetID_NGUOI_XEMNull() {
		pm_objDR["ID_NGUOI_XEM"] = System.Convert.DBNull;
	}

	public decimal dcNGAY 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "NGAY", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["NGAY"] = value;
		}
	}

	public bool IsNGAYNull()	{
		return pm_objDR.IsNull("NGAY");
	}

	public void SetNGAYNull() {
		pm_objDR["NGAY"] = System.Convert.DBNull;
	}

	public decimal dcTEN_TRAI_PHIEU 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TEN_TRAI_PHIEU", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TEN_TRAI_PHIEU"] = value;
		}
	}

	public bool IsTEN_TRAI_PHIEUNull()	{
		return pm_objDR.IsNull("TEN_TRAI_PHIEU");
	}

	public void SetTEN_TRAI_PHIEUNull() {
		pm_objDR["TEN_TRAI_PHIEU"] = System.Convert.DBNull;
	}

	public string strNOI_DUNG_NHAC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NOI_DUNG_NHAC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NOI_DUNG_NHAC"] = value;
		}
	}

	public bool IsNOI_DUNG_NHACNull() 
	{
		return pm_objDR.IsNull("NOI_DUNG_NHAC");
	}

	public void SetNOI_DUNG_NHACNull() {
		pm_objDR["NOI_DUNG_NHAC"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_RPT_NHAC_VIEC() 
	{
		pm_objDS = new DS_RPT_NHAC_VIEC();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_RPT_NHAC_VIEC(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_RPT_NHAC_VIEC(decimal i_dbID) 
	{
		pm_objDS = new DS_RPT_NHAC_VIEC();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
}
}
