///************************************************
/// Generated by: uyvq
/// Date: 08/09/2012 09:35:43
/// Goal: Create User Service Class for DM_THAM_SO_NHAC_VIEC
///************************************************
/// <summary>
/// Create User Service Class for DM_THAM_SO_NHAC_VIEC
/// </summary>


using BondDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using System;
namespace BondUS
{

public class US_DM_THAM_SO_NHAC_VIEC : US_Object
{
	private const string c_TableName = "DM_THAM_SO_NHAC_VIEC";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_TRAI_PHIEU 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_TRAI_PHIEU", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_TRAI_PHIEU"] = value;
		}
	}

	public bool IsID_TRAI_PHIEUNull()	{
		return pm_objDR.IsNull("ID_TRAI_PHIEU");
	}

	public void SetID_TRAI_PHIEUNull() {
		pm_objDR["ID_TRAI_PHIEU"] = System.Convert.DBNull;
	}

	public decimal dcID_LOAI_NHAC_VIEC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_NHAC_VIEC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_NHAC_VIEC"] = value;
		}
	}

	public bool IsID_LOAI_NHAC_VIECNull()	{
		return pm_objDR.IsNull("ID_LOAI_NHAC_VIEC");
	}

	public void SetID_LOAI_NHAC_VIECNull() {
		pm_objDR["ID_LOAI_NHAC_VIEC"] = System.Convert.DBNull;
	}

	public decimal dcSO_NGAY_NHAC_TRUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_NGAY_NHAC_TRUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_NGAY_NHAC_TRUOC"] = value;
		}
	}

	public bool IsSO_NGAY_NHAC_TRUOCNull()	{
		return pm_objDR.IsNull("SO_NGAY_NHAC_TRUOC");
	}

	public void SetSO_NGAY_NHAC_TRUOCNull() {
		pm_objDR["SO_NGAY_NHAC_TRUOC"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_THAM_SO_NHAC_VIEC() 
	{
		pm_objDS = new DS_DM_THAM_SO_NHAC_VIEC();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_THAM_SO_NHAC_VIEC(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_THAM_SO_NHAC_VIEC(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_THAM_SO_NHAC_VIEC();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion

    #region Additional Functions
    public void cap_nhat_tham_so_nhac_viec(decimal ip_dc_ngay_thanh_toan_lai
                                         , decimal ip_dc_ngay_thanh_toan_goc
                                         , decimal ip_dc_ngay_cap_nhat_lai_suat
                                         , decimal ip_dc_ngay_chot_ds_lai)
    {
        CStoredProc v_cstore = new CStoredProc("pr_DM_THAM_SO_NHAC_VIEC_cap_nhat_tham_so_nhac_viec");
        v_cstore.addDecimalInputParam("@NGAY_THANH_TOAN_LAI", ip_dc_ngay_thanh_toan_lai);
        v_cstore.addDecimalInputParam("@NGAY_THANH_TOAN_GOC", ip_dc_ngay_thanh_toan_goc);
        v_cstore.addDecimalInputParam("@NGAY_CAP_NHAT_LS", ip_dc_ngay_cap_nhat_lai_suat);
        v_cstore.addDecimalInputParam("@NGAY_CHOT_DS_LAI", ip_dc_ngay_chot_ds_lai);
        v_cstore.ExecuteCommand(this);
    }
    #endregion
}
}
