///************************************************
/// Generated by: linhdh
/// Date: 18/10/2012 06:37:26
/// Goal: Create User Service Class for V_DM_TO_CHUC_PHAT_HANH
///************************************************
/// <summary>
/// Create User Service Class for V_DM_TO_CHUC_PHAT_HANH
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using BondDS;


namespace BondUS{

public class US_V_DM_TO_CHUC_PHAT_HANH : US_Object
{
	private const string c_TableName = "V_DM_TO_CHUC_PHAT_HANH";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_TO_CHUC_PHAT_HANH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_TO_CHUC_PHAT_HANH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_TO_CHUC_PHAT_HANH"] = value;
		}
	}

	public bool IsMA_TO_CHUC_PHAT_HANHNull() 
	{
		return pm_objDR.IsNull("MA_TO_CHUC_PHAT_HANH");
	}

	public void SetMA_TO_CHUC_PHAT_HANHNull() {
		pm_objDR["MA_TO_CHUC_PHAT_HANH"] = System.Convert.DBNull;
	}

	public string strTEN_TO_CHUC_PHAT_HANH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_TO_CHUC_PHAT_HANH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_TO_CHUC_PHAT_HANH"] = value;
		}
	}

	public bool IsTEN_TO_CHUC_PHAT_HANHNull() 
	{
		return pm_objDR.IsNull("TEN_TO_CHUC_PHAT_HANH");
	}

	public void SetTEN_TO_CHUC_PHAT_HANHNull() {
		pm_objDR["TEN_TO_CHUC_PHAT_HANH"] = System.Convert.DBNull;
	}

	public string strDIA_CHI_TRU_SO_CHINH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DIA_CHI_TRU_SO_CHINH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DIA_CHI_TRU_SO_CHINH"] = value;
		}
	}

	public bool IsDIA_CHI_TRU_SO_CHINHNull() 
	{
		return pm_objDR.IsNull("DIA_CHI_TRU_SO_CHINH");
	}

	public void SetDIA_CHI_TRU_SO_CHINHNull() {
		pm_objDR["DIA_CHI_TRU_SO_CHINH"] = System.Convert.DBNull;
	}

	public string strMA_SO_THUE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_SO_THUE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_SO_THUE"] = value;
		}
	}

	public bool IsMA_SO_THUENull() 
	{
		return pm_objDR.IsNull("MA_SO_THUE");
	}

	public void SetMA_SO_THUENull() {
		pm_objDR["MA_SO_THUE"] = System.Convert.DBNull;
	}

	public string strDIEN_THOAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DIEN_THOAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DIEN_THOAI"] = value;
		}
	}

	public bool IsDIEN_THOAINull() 
	{
		return pm_objDR.IsNull("DIEN_THOAI");
	}

	public void SetDIEN_THOAINull() {
		pm_objDR["DIEN_THOAI"] = System.Convert.DBNull;
	}

	public string strFAX 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "FAX", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["FAX"] = value;
		}
	}

	public bool IsFAXNull() 
	{
		return pm_objDR.IsNull("FAX");
	}

	public void SetFAXNull() {
		pm_objDR["FAX"] = System.Convert.DBNull;
	}

	public string strCHUNG_NHAN_DKDN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "CHUNG_NHAN_DKDN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["CHUNG_NHAN_DKDN"] = value;
		}
	}

	public bool IsCHUNG_NHAN_DKDNNull() 
	{
		return pm_objDR.IsNull("CHUNG_NHAN_DKDN");
	}

	public void SetCHUNG_NHAN_DKDNNull() {
		pm_objDR["CHUNG_NHAN_DKDN"] = System.Convert.DBNull;
	}

	public string strSO_TAI_KHOAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SO_TAI_KHOAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SO_TAI_KHOAN"] = value;
		}
	}

	public bool IsSO_TAI_KHOANNull() 
	{
		return pm_objDR.IsNull("SO_TAI_KHOAN");
	}

	public void SetSO_TAI_KHOANNull() {
		pm_objDR["SO_TAI_KHOAN"] = System.Convert.DBNull;
	}

	public string strMO_TAI_NGAN_HANG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MO_TAI_NGAN_HANG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MO_TAI_NGAN_HANG"] = value;
		}
	}

	public bool IsMO_TAI_NGAN_HANGNull() 
	{
		return pm_objDR.IsNull("MO_TAI_NGAN_HANG");
	}

	public void SetMO_TAI_NGAN_HANGNull() {
		pm_objDR["MO_TAI_NGAN_HANG"] = System.Convert.DBNull;
	}

	public decimal dcID_NGUOI_LAP 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_LAP", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NGUOI_LAP"] = value;
		}
	}

	public bool IsID_NGUOI_LAPNull()	{
		return pm_objDR.IsNull("ID_NGUOI_LAP");
	}

	public void SetID_NGUOI_LAPNull() {
		pm_objDR["ID_NGUOI_LAP"] = System.Convert.DBNull;
	}

	public string strNGUOI_LAP 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NGUOI_LAP", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NGUOI_LAP"] = value;
		}
	}

	public bool IsNGUOI_LAPNull() 
	{
		return pm_objDR.IsNull("NGUOI_LAP");
	}

	public void SetNGUOI_LAPNull() {
		pm_objDR["NGUOI_LAP"] = System.Convert.DBNull;
	}

	public decimal dcID_NGUOI_DUYET 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_DUYET", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NGUOI_DUYET"] = value;
		}
	}

	public bool IsID_NGUOI_DUYETNull()	{
		return pm_objDR.IsNull("ID_NGUOI_DUYET");
	}

	public void SetID_NGUOI_DUYETNull() {
		pm_objDR["ID_NGUOI_DUYET"] = System.Convert.DBNull;
	}

	public string strNGUOI_DUYET 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NGUOI_DUYET", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NGUOI_DUYET"] = value;
		}
	}

	public bool IsNGUOI_DUYETNull() 
	{
		return pm_objDR.IsNull("NGUOI_DUYET");
	}

	public void SetNGUOI_DUYETNull() {
		pm_objDR["NGUOI_DUYET"] = System.Convert.DBNull;
	}

	public decimal dcID_TRANG_THAI 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_TRANG_THAI", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_TRANG_THAI"] = value;
		}
	}

	public bool IsID_TRANG_THAINull()	{
		return pm_objDR.IsNull("ID_TRANG_THAI");
	}

	public void SetID_TRANG_THAINull() {
		pm_objDR["ID_TRANG_THAI"] = System.Convert.DBNull;
	}

	public string strTRANG_THAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TRANG_THAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TRANG_THAI"] = value;
		}
	}

	public bool IsTRANG_THAINull() 
	{
		return pm_objDR.IsNull("TRANG_THAI");
	}

	public void SetTRANG_THAINull() {
		pm_objDR["TRANG_THAI"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_DM_TO_CHUC_PHAT_HANH() 
	{
		pm_objDS = new DS_V_DM_TO_CHUC_PHAT_HANH();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_DM_TO_CHUC_PHAT_HANH(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_DM_TO_CHUC_PHAT_HANH(decimal i_dbID) 
	{
		pm_objDS = new DS_V_DM_TO_CHUC_PHAT_HANH();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
