///************************************************
/// Generated by: NinhVH
/// Date: 06/12/2012 06:36:50
/// Goal: Create User Service Class for V_DM_DOT_PHAT_HANH_LAN_THU
///************************************************
/// <summary>
/// Create User Service Class for V_DM_DOT_PHAT_HANH_LAN_THU
/// </summary>


using BondDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using System;
namespace BondUS
{

    public class US_V_DM_DOT_PHAT_HANH_LAN_THU : US_Object
    {
        private const string c_TableName = "V_DM_DOT_PHAT_HANH_LAN_THU";
        #region Public Properties
        public decimal dcID
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID"] = value;
            }
        }

        public bool IsIDNull()
        {
            return pm_objDR.IsNull("ID");
        }

        public void SetIDNull()
        {
            pm_objDR["ID"] = System.Convert.DBNull;
        }

        public decimal dcID_TO_CHUC_PHAT_HANH
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_TO_CHUC_PHAT_HANH", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_TO_CHUC_PHAT_HANH"] = value;
            }
        }

        public bool IsID_TO_CHUC_PHAT_HANHNull()
        {
            return pm_objDR.IsNull("ID_TO_CHUC_PHAT_HANH");
        }

        public void SetID_TO_CHUC_PHAT_HANHNull()
        {
            pm_objDR["ID_TO_CHUC_PHAT_HANH"] = System.Convert.DBNull;
        }

        public DateTime datNGAY_PHAT_HANH
        {
            get
            {
                return CNull.RowNVLDate(pm_objDR, "NGAY_PHAT_HANH", IPConstants.c_DefaultDate);
            }
            set
            {
                pm_objDR["NGAY_PHAT_HANH"] = value;
            }
        }

        public bool IsNGAY_PHAT_HANHNull()
        {
            return pm_objDR.IsNull("NGAY_PHAT_HANH");
        }

        public void SetNGAY_PHAT_HANHNull()
        {
            pm_objDR["NGAY_PHAT_HANH"] = System.Convert.DBNull;
        }

        public decimal dcLAN_THU
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "LAN_THU", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["LAN_THU"] = value;
            }
        }

        public bool IsLAN_THUNull()
        {
            return pm_objDR.IsNull("LAN_THU");
        }

        public void SetLAN_THUNull()
        {
            pm_objDR["LAN_THU"] = System.Convert.DBNull;
        }

        #endregion


        #region Init Functions
        public US_V_DM_DOT_PHAT_HANH_LAN_THU()
        {
            pm_objDS = new DS_V_DM_DOT_PHAT_HANH_LAN_THU();
            pm_strTableName = c_TableName;
            pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
        }

        public US_V_DM_DOT_PHAT_HANH_LAN_THU(DataRow i_objDR)
            : this()
        {
            this.DataRow2Me(i_objDR);
        }

        public US_V_DM_DOT_PHAT_HANH_LAN_THU(decimal i_dbID)
        {
            pm_objDS = new DS_V_DM_DOT_PHAT_HANH_LAN_THU();
            pm_strTableName = c_TableName;
            IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
            v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
            SqlCommand v_cmdSQL;
            v_cmdSQL = v_objMkCmd.getSelectCmd();
            this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
            pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
        }
        #endregion

    }
}
